import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { UserService } from '../user.service';
import { IUser } from '../iuser';
import { BaseDetailsComponent, Globals, PickerDialogService, ErrorService } from 'src/app/common/shared';
import { GlobalPermissionService } from 'src/app/core/global-permission.service';

@Component({
  selector: 'app-user-details',
  templateUrl: './user-details.component.html',
  styleUrls: ['./user-details.component.scss'],
})
export class UserDetailsComponent extends BaseDetailsComponent<IUser> implements OnInit {
  title = 'User';
  parentUrl = 'user';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public global: Globals,
    public userService: UserService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, global, pickerDialogService, userService, errorService);
  }

  ngOnInit() {
    this.entityName = 'User';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
    this.setPickerSearchListener();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      emailAddress: ['', Validators.required],
      firstName: ['', Validators.required],
      id: [{ value: '', disabled: true }, Validators.required],
      isActive: [false, Validators.required],
      isEmailConfirmed: [false],
      lastName: ['', Validators.required],
      password: ['', Validators.required],
      phoneNumber: [''],
      userName: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'emailAddress',
        label: 'email Address',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'firstName',
        label: 'first Name',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'id',
        label: 'id',
        isRequired: true,
        isAutoGenerated: true,
        type: 'number',
      },
      {
        name: 'isActive',
        label: 'is Active',
        isRequired: true,
        isAutoGenerated: false,
        type: 'boolean',
      },
      {
        name: 'isEmailConfirmed',
        label: 'is Email Confirmed',
        isRequired: false,
        isAutoGenerated: false,
        type: 'boolean',
      },
      {
        name: 'lastName',
        label: 'last Name',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'password',
        label: 'password',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'phoneNumber',
        label: 'phone Number',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'userName',
        label: 'user Name',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
    ];
  }

  onItemFetched(item: IUser) {
    this.item = item;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'userId',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: true,
        table: 'userpermission',
        type: 'OneToMany',
        label: 'userpermissions',
      },
      {
        column: [
          {
            key: 'userId',
            value: undefined,
            referencedkey: 'id',
          },
        ],
        isParent: true,
        table: 'userrole',
        type: 'OneToMany',
        label: 'userroles',
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let user = this.itemForm.getRawValue();
    super.onSubmit(user);
  }
}
