import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormBuilder, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { StaffService } from '../staff.service';
import { IStaff } from '../istaff';
import { BaseDetailsComponent, Globals, PickerDialogService, ErrorService } from 'src/app/common/shared';
import { GlobalPermissionService } from 'src/app/core/global-permission.service';

import { AddressService } from 'src/app/entities/address/address.service';

@Component({
  selector: 'app-staff-details',
  templateUrl: './staff-details.component.html',
  styleUrls: ['./staff-details.component.scss'],
})
export class StaffDetailsComponent extends BaseDetailsComponent<IStaff> implements OnInit {
  title = 'Staff';
  parentUrl = 'staff';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public global: Globals,
    public staffService: StaffService,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService,
    public addressService: AddressService,
    public globalPermissionService: GlobalPermissionService
  ) {
    super(formBuilder, router, route, dialog, global, pickerDialogService, staffService, errorService);
  }

  ngOnInit() {
    this.entityName = 'Staff';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
    this.setPickerSearchListener();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      active: [false, Validators.required],
      email: [''],
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      lastUpdate: ['', Validators.required],
      lastUpdateTime: ['', Validators.required],
      password: [''],
      staffId: [{ value: '', disabled: true }, Validators.required],
      storeId: ['', Validators.required],
      username: ['', Validators.required],
      addressId: ['', Validators.required],
      addressDescriptiveField: ['', Validators.required],
    });

    this.fields = [
      {
        name: 'active',
        label: 'active',
        isRequired: true,
        isAutoGenerated: false,
        type: 'boolean',
      },
      {
        name: 'email',
        label: 'email',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'firstName',
        label: 'first Name',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'lastName',
        label: 'last Name',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'lastUpdate',
        label: 'last Update',
        isRequired: true,
        isAutoGenerated: false,
        type: 'date',
      },
      {
        name: 'lastUpdateTime',
        label: 'last Update Time',
        isRequired: true,
        isAutoGenerated: false,
        type: 'time',
      },
      {
        name: 'password',
        label: 'password',
        isRequired: false,
        isAutoGenerated: false,
        type: 'string',
      },
      {
        name: 'storeId',
        label: 'store Id',
        isRequired: true,
        isAutoGenerated: false,
        type: 'number',
      },
      {
        name: 'username',
        label: 'username',
        isRequired: true,
        isAutoGenerated: false,
        type: 'string',
      },
    ];
  }

  onItemFetched(item: IStaff) {
    this.item = item;
    this.itemForm.patchValue(item);
    this.itemForm.get('lastUpdate').setValue(item.lastUpdate ? new Date(item.lastUpdate) : null);
    this.itemForm.get('lastUpdateTime').setValue(this.staffService.formatDateStringToAMPM(item.lastUpdate));
  }

  setAssociations() {
    this.associations = [
      {
        column: [
          {
            key: 'addressId',
            value: undefined,
            referencedkey: 'addressId',
          },
        ],
        isParent: false,
        table: 'address',
        type: 'ManyToOne',
        label: 'address',
        service: this.addressService,
        descriptiveField: 'addressDescriptiveField',
        referencedDescriptiveField: 'addressId',
      },
      {
        column: [
          {
            key: 'staffId',
            value: undefined,
            referencedkey: 'staffId',
          },
        ],
        isParent: true,
        table: 'payment',
        type: 'OneToMany',
        label: 'payments',
      },
      {
        column: [
          {
            key: 'staffId',
            value: undefined,
            referencedkey: 'staffId',
          },
        ],
        isParent: true,
        table: 'rental',
        type: 'OneToMany',
        label: 'rentals',
      },
      {
        column: [
          {
            key: 'managerStaffId',
            value: undefined,
            referencedkey: 'storeId',
          },
        ],
        isParent: true,
        table: 'store',
        type: 'OneToOne',
        label: 'store',
        associatedPrimaryKeys: ['storeId'],
      },
    ];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let staff = this.itemForm.getRawValue();
    staff.lastUpdate = this.dataService.combineDateAndTime(staff.lastUpdate, staff.lastUpdateTime);
    delete staff.lastUpdateTime;
    super.onSubmit(staff);
  }
}
